---
# tasks file for nutanix_role_prism_container_search
- include_tasks: setup_api.yml

- name: Fail if "{{ nutanix_host }}" is not a Prism Element cluster
  ansible.builtin.fail:
    msg: "this role can only be run against a Nutanix cluster"
  when:
    - nutanix_endpoint_prism_type != 'pe'

- name: Find uuid for container "{{ nutanix_container_search_name }}" on "{{ nutanix_host }}"
  block:
    - name: Get containers from Prism API
      uri:
        url: "https://{{nutanix_host}}:{{nutanix_port}}/PrismGateway/services/rest/v2.0/storage_containers"
        method: GET
        validate_certs: "{{ validate_certs }}"
        body_format: json
        headers:
          Authorization: "{{ nutanix_api_auth }}"
        status_code: 200
        return_content: yes
      register: nutanix_current_containers
      ignore_errors: no

    - name: Search container list for container name and return its uuid
      set_fact:
        nutanix_container_found_uuid: "{{ item }}"
      with_items: "{{ nutanix_current_containers.json | to_json | from_json | json_query(query) }}"
      vars:
        query: "entities[?name=='{{ nutanix_container_search_name }}'].storage_container_uuid"
      when: nutanix_current_containers.json.metadata.total_entities > 0

    - name:
      debug:
        msg: "uuid='{{ nutanix_container_found_uuid }}', container_name='{{ nutanix_container_search_name }}' on Prism Element '{{ nutanix_host }}'"
      when: nutanix_container_found_uuid is defined

    - name:
      debug:
        msg: "uuid=null, container_name='{{ nutanix_container_search_name }}' on Prism Element '{{ nutanix_host }}'"
      when: nutanix_container_found_uuid is not defined
